// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"database/sql"
)

type Author struct {
	ID    int32
	Email string
	Name  string
}

type Post struct {
	ID        int32
	Title     string
	Content   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Author    int32
}
