// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in app/entity/runtime.go

const (
	Version = "v0.12.3"                                         // Version of ent codegen.
	Sum     = "h1:N5lO2EOrHpCH5HYfiMOCHYbo+oh5M8GjT0/cx5x6xkk=" // Sum of ent codegen.
)
