// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Author           string
	Post             string
	SchemaMigrations string
}{
	Author:           "author",
	Post:             "post",
	SchemaMigrations: "schema_migrations",
}
